name: Stock Screening
on:
  schedule:
    - cron: '0 21 * * 0-4'  # 每個工作日早上 5:00 (UTC+8) 運行
  workflow_dispatch:  # 允許手動觸發
jobs:
  screen:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN }}  
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
         python-version: '3.11'  
         
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run screening script
      env:
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        RECIVER_EMAIL: ${{ secrets.RECIVER_EMAIL }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      run: python 動能選股.py
    
    - name: Archive historical data
      run: python archive_data.py
    
    - name: Generate stock price data for web
      run: python generate_stock_data.py
    
    - name: Copy historical data to web folder
      run: |
        cp historical_data.json web/historical_data.json
        echo "✅ Copied historical_data.json to web folder"

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add stocks_data.json historical_data.json web/stock_price_data.json web/historical_data.json
        git commit -m "更新股票數據和價格圖表數據 $(date +'%Y-%m-%d')" || echo "無變更"
        git push
